### PR TITLE
Restricted the input boxes

### PR DESCRIPTION
**Pull request by arkumari2000**
## Related Issuse

- The issue was that there was no restriction on the limit of input length in the class name and subject code while creating class.

Closes: #109 

#### Describe the changes you've made

I have put a restriction of length limit 12 to the class code and subject code in the createClass form.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings.

### CODE REVIEW

**Comment by iamabhi222** [comment]
I think  inputProps={{   maxLength: 12  }}  will not work with type='number'

**Comment by arkumari2000** [comment]
yes you are right, we can do one thing. `max="999999999999"` with `type='number'` so that only 12 digit numbers can be accepted , will it be a good solution?

**Comment by iamabhi222** [comment]
Instead you can use  
> onInput={(e) => {
              e.target.value = Math.max(0, parseInt(e.target.value))
                .toString()
                .slice(0, 12);
            }}

**Comment by arkumari2000** [comment]
yeah that can also be done. 
Can you tell me the route to access the createClass form, so that I can test this? I tried to find, but didn't find it.

**Comment by arkumari2000** [comment]
Now please review. I have done recommended changes and tested too.

**Pull request closed without merging**
