### PR TITLE
auto assign issue

### PR DESCRIPTION
**Pull request by imakash3011**
## Inputs

| Parameter    | Required | Description                                                                |
| ------------ | -------- | -------------------------------------------------------------------------- |
| `repo-token` | true     | The GITHUB_TOKEN, needed to update the Issue.                              |
| `assignees`  | true     | Comma separated list of user names. Issue will be assigned to those users. |

Follow above command to auto assign issue.

### CODE REVIEW

**Comment by aavishkarmishra** [comment]
Hello, @imakash3011  we do not require auto assign as I am assigning issues because of SWoC guidelines otherwise issues will be open for everyone to create pull requests.

**Comment by imakash3011** [comment]
@aavishkarmishra could you please tell me what we have to do then??

**Comment by aavishkarmishra** [comment]
You work on the issues and try resolve them ? 
If need any help regarding that you can ping me.

**Comment by imakash3011** [comment]
Ohh.. sorry @aavishkarmishra  I was making this GitHub action for any other issue and by mistake i made a PR to this Repo. I'm  sorry  for this .

**Pull request closed without merging**
