### PR TITLE
Custom Theme 

### PR DESCRIPTION
**Pull request by nishant23122000**
## Related Issuse

- Apply Custom theming on platofrm

Closes: #149

#### Describe the changes you've made

As I describe in issue #149, I made a change in the frontend and backend both, 
You can see in file changes where I create UI reducer and UI action file and also /user/theme API endpoint for saving the selected user theme so that we can fetch there when user load.

Also, there is a feature to preview the theme by clicking on a theme that the user wants to change and this will apply to the whole page as a preview

There is one default theme which will be automatic saved when new user register.
Check below video

https://user-images.githubusercontent.com/53515714/113502124-d4c79b80-9547-11eb-9ed2-072e4a0a73bc.mp4

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|      Original       |      Updated       |
| :-----------------: | :----------------: |
| original screenshot | updated screenshot |

### CODE REVIEW

**Review by aavishkarmishra — CHANGES_REQUESTED** [review]
There are few issues : 
- Themes are only applied to dashboard.
- Transparent navbar disappears in other views.   
- UI of lading page is changed.

Screenshot from 2021-04-04 16-24-57

Please look into these...

**Comment by nishant23122000** [comment]
> There are few issues :
> 
> * Themes are only applied to dashboard.
> * Transparent navbar disappears in other views.
> * UI of lading page is changed.
> 
> Screenshot from 2021-04-04 16-24-57
> 
> Please look into these...

Hey Can you check it now, I think now I remove all the UI issue that you mention and also some others, still please inform me if any issue is there

**Comment by aavishkarmishra** [comment]
> > There are few issues :
> > 
> > * Themes are only applied to dashboard.
> > * Transparent navbar disappears in other views.
> > * UI of lading page is changed.
> > 
> > Screenshot from 2021-04-04 16-24-57
> > Please look into these...
> 
> Hey Can you check it now, I think now I remove all the UI issue that you mention and also some others, still please inform me if any issue is there

Check out for not found page too.

**Comment by nishant23122000** [comment]
> > > There are few issues :
> > > 
> > > * Themes are only applied to dashboard.
> > > * Transparent navbar disappears in other views.
> > > * UI of lading page is changed.
> > > 
> > > Screenshot from 2021-04-04 16-24-57
> > > Please look into these...
> > 
> > 
> > Hey Can you check it now, I think now I remove all the UI issue that you mention and also some others, still please inform me if any issue is there
> 
> Check out for not found page too.

Now it's visible

**Comment by nishant23122000** [comment]
Hey, @aavishkarmishra  Can you please add GSSOC label.

**Pull request merged**
