### PR TITLE
fix: Problem in AppBar of Navbar

### PR DESCRIPTION
**Pull request by hsnice16**
## Related Issues

The problem in App Bar of Navbar

Closes: #167

#### Describe the changes you've made

I changed some lines of code in client/src/components/layout/Navbar.js

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.

## Screenshots

|      Original       |      Updated       |
| :-----------------: | :----------------: |
| image | image |

### CODE REVIEW

**Review by iamabhi222 — CHANGES_REQUESTED** [review]
> const getTheme = ['/dashboard', '/class/'].includes(location.pathname)

this will return false even if we are at /class/* route thus the navbar will not be transparent for /class routes

**Comment by hsnice16** [comment]
Thanks @iamabhi222 , This will work right ?
const pathname = location.pathname; 
const getTheme = pathname.includes('/dashboard') || pathname.includes('/class/');

**Comment by hsnice16** [comment]
@iamabhi222 Please guide me.

**Comment by iamabhi222** [comment]
> Thanks @iamabhi222 , This will work right ?
> const pathname = location.pathname;
> const getTheme = pathname.includes('/dashboard') || pathname.includes('/class/');

yes looks good!

**Comment by iamabhi222** [comment]
make the commit

**Comment by hsnice16** [comment]
Okay

**Comment by hsnice16** [comment]
Please merge it.

**Comment by hsnice16** [comment]
Thanks for merging

**Pull request merged**
