### PR TITLE
Fixed issue "Questions with no content/options can be added "

### PR DESCRIPTION
**Pull request by RitikPandey1**
bug fixed 
bug description :  #12  

whenever user try to add question without any content error message will display at bottom

error1

### CODE REVIEW

**Comment by RitikPandey1** [comment]
@aavishkarmishra,  please review this PR and also add SWOC label

**Comment by mohit355** [comment]
@RitikPandey1  attach a snapshot of the error message popup

**Comment by RitikPandey1** [comment]
> @RitikPandey1 attach a snapshot of the error message popup
Already attached in initial comment please check

**Review by mohit355 — APPROVED** [review]

**Comment by aavishkarmishra** [comment]
Thanks @RitikPandey1 and @mohit355

**Pull request merged**
