### PR TITLE
class link

### PR DESCRIPTION
**Pull request by nishant23122000**
As I proposed before, a new feature where users can create classlink so that they can share this link to others.

Check below steps to show how the flow of this feature works

STEP 1 : user creates a class

STEP 2 : user will find the copy class link button under the Enrolled section, for his desired class.

Capture

STEP 3 : The user will copy the link and now he will be able to share this link with his friend

STEP 4 : his friend open this link and reached at join/classcode URL

STEP 5: if his friend is not logged in then he gets a warning to log in for joining the class

STEP 6 : if his friend has already joined the class then an alert message is prompted and redirected to the home page

STEP  7 : if a user is logged in and not already in class then he will join the class and redirect to the homepage where he can see that he joined the class

I also removed a recent bug where hours were mandatory in class test form. so also check this.

### CODE REVIEW

**Comment by Deeksha2501** [comment]
Does the user(friend) be alerted with a confirmation message (Do you want to join class "classname")?

**Comment by nishant23122000** [comment]
@Deeksha2501  Yes, when user(friend) open link, then there is one confirmation UI render

**Comment by Deeksha2501** [comment]
Can you send us a screen recording of the functionality?

**Comment by nishant23122000** [comment]
sure, you can check this.

The video tutorial shows 2 scenarios. One: the user hasn't already joined the classroom, in which case, he presses 'Yes' to join it. Two: He has already joined it, in which case he will be redirected to his homepage on pressing 'Yes'

https://user-images.githubusercontent.com/53515714/111293458-4dd18280-866f-11eb-84d7-6f899fa491e3.mp4

**Comment by Deeksha2501** [comment]
Nicee ✨

**Comment by Deeksha2501** [comment]
Can you please add the name of class in the confirmation message?

**Comment by nishant23122000** [comment]
@Deeksha2501 I will add the class name in the confirmation message in my next pull request.

**Comment by Deeksha2501** [comment]
Okayy

**Pull request merged**
