### PR TITLE
Fixed issue "Unable to create a class"

### PR DESCRIPTION
**Pull request by RitikPandey1**
issue #5 resolved

### CODE REVIEW

**Comment by mohit355** [comment]
Hey, @RitikPandey1  attach a snapshot of UI changes.

**Review by harshareddy794 — APPROVED** [review]
LGTM! @RitikPandey1 
Thanks for your contribution

**Comment by RitikPandey1** [comment]
> Hey, @RitikPandey1 attach a snapshot of UI changes.

now user can create class without subject and subject code
snapshot1
snapshot2

**Comment by RitikPandey1** [comment]
> LGTM! @RitikPandey1
> Thanks for your contribution

Thanks :)

**Review by mohit355 — APPROVED** [review]

**Comment by RitikPandey1** [comment]
@aavishkarmishra could you add SWOC label in this PR

**Comment by RitikPandey1** [comment]
@vikhyatsingh123, please review my PR.

**Pull request merged**
