### PR TITLE
Add Class Image 

### PR DESCRIPTION
**Pull request by nishant23122000**
## Related Issue
Allow creating a class image
Close :  #135

#### Describe the changes you've made

As I mentioned in issue #135, we should add a class image, So I implement this feature by adding multer npm in the backend, you can check the full video below

## Checklist:

- [ ✔] My code follows the style guidelines of this project.
- [✔ ] I have performed a self-review of my own code.
- [ ✔] I have commented on my code, particularly in hard-to-understand areas.
- [ ✔] I have made corresponding changes to the documentation.
- [ ✔] My changes generate no new warnings.

## Screenshots

https://user-images.githubusercontent.com/53515714/113410201-762be180-93d0-11eb-83d4-2e009471757f.mp4

### CODE REVIEW

**Comment by aavishkarmishra** [comment]
Please add a default image for background, if someone doesn't want to add images and don't make it necessary.

**Comment by nishant23122000** [comment]
@aavishkarmishra Oh yes, I forgot this point, ok no problem, Now check it please

https://user-images.githubusercontent.com/53515714/113413689-db83d080-93d8-11eb-8baa-33867d907e53.mp4

**Review by Vidisha-kayal — APPROVED** [review]

**Comment by nishant23122000** [comment]
@Vidisha-kayal  Hey can you please add GSSOC level and label in this and #69 PR

**Comment by aavishkarmishra** [comment]
> @Vidisha-kayal Hey can you please add GSSOC level and label #69 PR

@nishant23122000 #69 is closed, so adding labels will not make any effect.

**Comment by nishant23122000** [comment]
@aavishkarmishra  sorry , my mistake . I just show this PR and it's older version of PR #72

**Pull request merged**
