### PR TITLE
Fixed #51 Aligned Number of Enrolled

### LINKED ISSUE #51: Not properly aligned number of enrolled
**Describe the bug**
In the navigation bar, under the enrolled the number of enrolled is not aligned properly.

**To Reproduce**
1. Go to `http://www.manthan-app.org/`
2. Click on 'Navigation three line'
3. Under the `enrolled`

**Expected behavior**
It should be aligned just below the enrolled button and also in bold to show the importance of the enrolled number.

**Screenshots**
Capsture

**Desktop (please complete the following information):**
 

**Additional context**
If you would like then I will fix the issue.

### PR DESCRIPTION
**Pull request by Abhishek765**
Issue: #51

fixed: Alignment
image

### CODE REVIEW

**Comment by Abhishek765** [comment]
Kindly review it, and let me know if I miss something

**Comment by Abhishek765** [comment]
Also, I request @aavishkarmishra to label the issue as `gssoc21` as it is mentioned in FAQs in discord

**Comment by iamabhi222** [comment]
I think that's not the perfect solution as its changing the orientation when we have some enrolled classes

**Comment by iamabhi222** [comment]
also check the orientation after we have some enrolled classes!
image

**Comment by Abhishek765** [comment]
> also check the orientation after we have some enrolled classes!
> image



OK, I think you're pointing like this I guess?? Like some padding is created on the left side?

image

**Comment by iamabhi222** [comment]
> > also check the orientation after we have some enrolled classes!
> > image
> 
> OK, I think you're pointing like this I guess?? Like some padding is created on the left side?
> 
yes and also  <ListSubheader> gives a faded color to the enrolled classes please see to it also

**Comment by Abhishek765** [comment]
@iamabhi222  Check this one So that I can create another PR for the same


image

**Comment by Abhishek765** [comment]
Please review and let me know if it fine

**Comment by iamabhi222** [comment]
> Please review and let me know if it fine

please check the color of text and also I don't think its required to set the .env path, what do you think @aavishkarmishra ?

**Comment by iamabhi222** [comment]
> Please review and let me know if it fine

please check the color of text and also I don't think its required to set the .env path, what do you think @aavishkarmishra ?

**Comment by iamabhi222** [comment]
just place the .env at root of server

**Comment by Abhishek765** [comment]
> just place the .env at root of server

Yes Actually I already placed the .env in the root folder that's why I changed the Path

**Comment by Abhishek765** [comment]
> > Please review and let me know if it fine
> 
> please check the color of text and also I don't think its required to set the .env path, what do you think @aavishkarmishra ?

Sorry for the Color will be done soon

**Comment by Abhishek765** [comment]
Done: I guess

image


image

**Comment by aavishkarmishra** [comment]
> just place the .env at root of server

I think so as .env file is related to server, so it will be better to place it in root of server.

**Comment by iamabhi222** [comment]
make a fresh PR with only the required changes(dont change .env path) and we can merge also check the merge conflict

**Pull request closed without merging**
