### PR TITLE
added a homepage

### PR DESCRIPTION
**Pull request by mis-coder**
I have added a home page for Manthan, which contains introduction about the Manthan and a button 'get started', which further takes user to the main page which was initially the home page.

Closes: #122 

#### Describe the changes you've made

I have created a home component inside view -> home. In the same folder I have added a css module file for styling. I have added route in the app.js for home component. 

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots
Previously it was only this:
manthan-prev

Now I have added another home page:
Manthan Home Page

### CODE REVIEW

**Comment by Vidisha-kayal** [comment]
@mis-coder Can you make the page more responsive?

**Comment by mis-coder** [comment]
> @mis-coder Can you make the page more responsive?
Okay i will do that. You can also tell me if you have any preferences i will change things

**Comment by mis-coder** [comment]
> @mis-coder Can you make the page more responsive?

Hi! I just wanted to clear that do you want me to fix the ui which breaks at certain points or do you also want to change the layout on small devices?

**Comment by mis-coder** [comment]
> @mis-coder Can you make the page more responsive?
Have a look now

https://user-images.githubusercontent.com/51118723/112447222-12be0600-8d77-11eb-85a2-7b389e26d772.mp4

**Review by Vidisha-kayal — APPROVED** [review]

**Pull request merged**
