### PR TITLE
Implementing Token Based Authentication and authorization

### PR DESCRIPTION
**Pull request by osamamagdy**
## Related Issues

- Tests can be created anonymously 
- Creation of tests should only be limited to the teacher (Google Classrooms assumes this is the creator of the test). But the current system allows not only a random user logged in to create tests but also anonymous users on the internet. This is a basic security requirement, and that would prevent anyone from using this app in a serious environment.

Closes: #83 #119 

#### Describe the changes you've made
Using the User schema, when a user is logged in or signed up to the website --> we create a jwt with cookies in the browser that stores the necessary information.
I wrote auth middleware functions that check whether the user is a teacher or a general user of the website through decoding the previously-stored jwt.

## Checklist:

<!--
Example how to mark a checkbox:-
- [x] My code follows the code style of this project.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

### CODE REVIEW

**Comment by aavishkarmishra** [comment]
@osamamagdy can you integrate this authentication with google login, as we use google login for signin and signout.

**Comment by osamamagdy** [comment]
@aavishkarmishra of course i can but i can't find the file where the function of signing up is added. Can you guide me to its path in the repo?

**Comment by osamamagdy** [comment]
@aavishkarmishra Done now

**Comment by osamamagdy** [comment]
@aavishkarmishra Is this still pending review?

**Review by iamabhi222 — APPROVED** [review]

**Comment by osamamagdy** [comment]
Hello @Deeksha2501 , I need your review for this

**Pull request merged**
