### PR TITLE
Added LOGIN WITH FACEBOOK feature (#47)

### PR DESCRIPTION
**Pull request by Itsaadarsh**
## Related Issuse
This issue is related to adding more login feature to the platform (#47)

Closes: #47 

#### Describe the changes you've made

Added LOGIN WITH FACEBOOK feature using `react-login-facebook` library, where we need to provide an APPID to the Facebook login component and it automatically calls the Facebook APIs for the login info once the user is logged in we persist the user data onto local storage and on logging out we delete that data. 

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|      Original       |      Updated       |
| :-----------------: | :----------------: |
| image | image |

### CODE REVIEW

**Comment by Deeksha2501** [comment]
Please add a screen recording of how it works.

**Comment by Itsaadarsh** [comment]
@Deeksha2501 Here you go!
https://user-images.githubusercontent.com/54549066/111185495-06e47e00-85d8-11eb-8d86-167a19187150.mp4

**Comment by Itsaadarsh** [comment]
@Deeksha2501 Here you go!
https://user-images.githubusercontent.com/54549066/111186049-a30e8500-85d8-11eb-87fa-4994cd97b67c.mp4

**Comment by Deeksha2501** [comment]
> @Deeksha2501 Here you go!
> https://user-images.githubusercontent.com/54549066/111186049-a30e8500-85d8-11eb-87fa-4994cd97b67c.mp4

Nicee✨

**Pull request merged**
