### PR TITLE
horizontal scroll bar fixed

### PR DESCRIPTION
**Pull request by VenomFate-619**
## Related Issues

- Info about Issue or bug

Closes: #164 

A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!
Just make a change in css 

## Checklist:

- [ x] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ x] My changes generate no new warnings.

## Screenshots

original screenshot 
image
updated screenshot 
image

### CODE REVIEW

**Review by iamabhi222 — COMMENTED** [review]
> import { Typography, Grid, Container, Paper } from '@material-ui/core'

where have you used Paper component? and also giving classContainer a width of 100% will not make any change

**Comment by VenomFate-619** [comment]
The Paper component was imported by mistake (sorry for that). `width:100%` will make a change in /dashboard route it 
will **remove the negative margin** which is there due to `margin:0 auto`

**Comment by iamabhi222** [comment]
ok make the PR clean

**Comment by VenomFate-619** [comment]
@iamabhi222 can I make the changes in my next PR , as I had made changes in files for my upcoming PR for issue #170

**Comment by iamabhi222** [comment]
yes

**Pull request closed without merging**
